baseurl = "https://www.skribgit.com/devops/blog/"
title = "SkribGit, Inc. Live By Design. Work By Design."
copyright = "Copyright &copy; 2018 - SkribGit, Inc."
canonifyurls = true
theme = "kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "Radamanthus Batnag"
    github = "radamanthus"
    linkedin = "radamanthus"
    twitter = "radamanthus"

[params]
    tagline = "Live By Design. Work By Design."



